apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: gcr.io/YOUR_PROJECT_ID/container2:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /disha_PV_dir
              name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: disha-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
